# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0776e796f9506e4ffedafae9c81373e6ea478e6accdbc61153bf6cc7d922362b8a935960ae8d7f06667eb94b10f667158ef8a5912932f2f6a31bd851904eef8e

test:
  secret_key_base: e86e9bb4d9c7c29252b10a6af75abe4f0c56d1c8c7dd404c408ea826a9d12e2c3309edb2f9255dd9287cdd386f01a0cde8162f4ae9cc8e8ba3316f6259033d4b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
